name: metrix
description: "Offline-first meter reading application"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.22

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.9.0
  flutter_riverpod: ^2.6.1
  sqflite: ^2.4.2
  path: ^1.9.1

  connectivity_plus: ^6.1.5

  # Image & EXIF metadata
  image_picker: ^0.8.4+11
  exif: ^3.3.0
  flutter_native_splash: ^2.4.6

  # Location
  geolocator: ^14.0.1

  # Auth
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  mime: ^1.0.2

  # Utils
  uuid: ^4.5.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1

  shared_preferences: ^2.5.3

  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  package_info_plus: ^9.0.0
  open_filex: ^4.7.0

  flutter_dotenv: ^6.0.0
  flutter_downloader: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.5.0
  freezed: ^3.1.0
  build_runner: ^2.7.0

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # assets:
  #   - .env
  #   - assets/img/