name: metrix
description: "Offline-first meter reading application"

publish_to: 'none'


version: 1.0.25

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.9.0
  flutter_riverpod: ^2.6.1
  sqflite: ^2.4.2
  path: ^1.9.1

  connectivity_plus: ^6.1.5

  # Image & EXIF metadata
  image_picker: ^0.8.4+11
  exif: ^3.3.0
  flutter_native_splash: ^2.4.6

  # Location
  geolocator: ^14.0.1

  # Auth
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  mime: ^1.0.2

  # Utils
  uuid: ^4.5.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1

  shared_preferences: ^2.5.3

  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  package_info_plus: ^9.0.0
  open_filex: ^4.7.0

  flutter_dotenv: ^6.0.0
  flutter_downloader: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.5.0
  freezed: ^3.1.0
  build_runner: ^2.7.0

  flutter_lints: ^5.0.0

flutter:

 
  uses-material-design: true
