name: Build and Upload APK to Beget S3

on:
  push:
    tags:
      - 'v*.*.*' # déclenche uniquement pour les tags commençant par "v", ex: v1.2.0
  # Ou bien pour publier uniquement lors d'une release :
  # release:
  #   types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java (AGP requires Java 17+)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # change to 21 if you upgrade AGP later

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3' # ✅ corrigé (pas d’espace)
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Update Flutter dependencies
        run: flutter pub upgrade

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: 'upload-keystore.jks'
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      - name: Move keystore into android/app
        run: |
          mkdir -p android/app
          mv "${{ steps.android_keystore.outputs.filePath }}" "android/app/upload-keystore.jks"
          ls -la android/app

      - name: Create key.properties
        run: |
          cat > android/key.properties <<'EOF'
          storePassword=${{ secrets.KEY_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=upload-keystore.jks
          EOF
          echo "== key.properties =="
          cat android/key.properties

      - name: Sanity check files
        run: |
          pwd
          ls -la android
          ls -la android/app
          test -f android/app/upload-keystore.jks || (echo "Keystore missing" && exit 1)

      - name: Build APK
        run: flutter build apk --release
        # Output : build/app/outputs/flutter-apk/app-release.apk

      # - name: Configure AWS credentials for Beget S3
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.BEGET_S3_ACCESS_KEY }}
      #     aws-secret-access-key: ${{ secrets.BEGET_S3_SECRET_KEY }}
      #     aws-region: ${{ secrets.BEGET_S3_REGION }}

      - name: Upload APK to Beget S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BEGET_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BEGET_S3_SECRET_KEY }}
          AWS_DEFAULT_REGION: ru-1 # n’a pas d’importance, mais l’AWS CLI l’exige
          AWS_EC2_METADATA_DISABLED: 'true'
          ENDPOINT: ${{ secrets.BEGET_S3_ENDPOINT_URL }} # ex: https://s3.ru1.storage.beget.cloud
          BUCKET: ${{ secrets.BEGET_S3_BUCKET_NAME }}
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          FILE=build/app/outputs/flutter-apk/app-release.apk
          DEST=apk/my_app_v${VERSION:-latest}.apk

          # (Optionnel) vérifier la présence du fichier
          test -f "$FILE" || (echo "APK introuvable: $FILE" && exit 1)

          echo "Uploading $FILE → s3://$BUCKET/$DEST"
          aws s3 cp "$FILE" "s3://$BUCKET/$DEST" \
            --endpoint-url "$ENDPOINT" \
            --acl public-read \
            --only-show-errors

          echo "✅ Upload OK."
          echo "URL (path-style): $ENDPOINT/$BUCKET/$DEST"
          echo "URL (virtual-hosted, si supporté): https://$BUCKET.${ENDPOINT#https://}/$DEST"
