name: Build and Upload APK to Beget S3

on:
  push:
    tags:
      - 'v*.*.*' # déclenche uniquement pour les tags commençant par "v", ex: v1.2.0
  # Ou bien pour publier uniquement lors d'une release :
  # release:
  #   types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java (AGP requires Java 17+)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # change to 21 if you upgrade AGP later

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3' # ✅ corrigé (pas d’espace)
          channel: 'stable'

      - name: Create keystore file
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" > android/app/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/app/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/app/key.properties
          echo "storeFile=upload-keystore.jks" >> android/app/key.properties

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Update Flutter dependencies
        run: flutter pub upgrade

      - name: Build APK
        run: flutter build apk --release
        # Output : build/app/outputs/flutter-apk/app-release.apk

      - name: Configure AWS credentials for Beget S3
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.BEGET_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.BEGET_S3_SECRET_KEY }}
          aws-region: ru-1 # région fictive, pas utilisé par Beget

      - name: Upload APK to Beget S3
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          FILE=build/app/outputs/flutter-apk/app-release.apk
          DEST=apk/my_app_v${VERSION:-latest}.apk

          echo "Uploading $FILE to bucket..."
          aws --endpoint-url ${{ secrets.BEGET_S3_ENDPOINT_URL }} \
              s3 cp $FILE s3://${{ secrets.BEGET_S3_BUCKET_NAME }}/$DEST \
              --acl public-read

          echo "✅ APK uploaded to:"
          echo "https://${{ secrets.BEGET_S3_BUCKET_NAME }}.${{ secrets.BEGET_S3_ENDPOINT_URL }}/$DEST"
